language: rust
rust:
    - stable
    - beta
    - nightly
notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
    - cargo build --verbose
    - cargo test --verbose -- --nocapture

