[package]
name = "folia"
version = "0.0.1"
authors = ["Maarten van Gompel <proycon@anaproy.nl>"]
edition = "2018"

[dependencies]
quick-xml = "0.16.0"
matches = "0.1.8"
strum = "0.16.0"
strum_macros = "0.16.0"
clap = "2.33.0"
